- job:
    name: blazar-devstack-dsvm
    parent: legacy-dsvm-base
    irrelevant-files:
      - ^.*\.rst$
      - ^blazar/tests/.*$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^test-requirements.txt$
      - ^tools/.*$
      - ^tox.ini$
    run: playbooks/legacy/blazar-devstack-dsvm/run.yaml
    post-run: playbooks/legacy/blazar-devstack-dsvm/post.yaml
    timeout: 4200
    required-projects:
      - openstack-dev/devstack
      - openstack-infra/devstack-gate
      - openstack/blazar
      - openstack/blazar-nova
      - openstack/python-blazarclient
      - openstack/blazar-tempest-plugin

- project:
    check:
      jobs:
        - blazar-devstack-dsvm
    gate:
      jobs:
        - blazar-devstack-dsvm
